--
--  File: list_non_default_roles.sql
--
--  Author: Ron Reidy
--
--  Description:  Use this script to list non-default (built in) roles
--
-- This script comes with no warranty ...use at own risk 
-- Copyright (C) 2014  Ron Reidy
-- 
-- This program is free software; you can redistribute it and/or modify 
-- it under the terms of the GNU General Public License as published by 
-- the Free Software Foundation; version 2 of the License. 
-- 
-- This program is distributed in the hope that it will be useful, 
-- but WITHOUT ANY WARRANTY; without even the implied warranty of 
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
-- GNU General Public License for more details. 
-- 
-- You should have received a copy of the GNU General Public License 
-- along with this program or from the site that you downloaded it 
-- from; if not, write to the Free Software Foundation, Inc., 59 Temple 
-- Place, Suite 330, Boston, MA  02111-1307   USA
--
WITH def_roles AS (
SELECT 'ADM_PARALLEL_EXECUTE_TASK' FROM dual
UNION
SELECT 'AQ_ADMINISTRATOR_ROLE' FROM dual
UNION
SELECT 'AQ_USER_ROLE' FROM dual
UNION
SELECT 'AUTHENTICATEDUSER' FROM dual
UNION
SELECT 'CAPI_USER_ROLE' FROM dual
UNION
SELECT 'CONNECT' FROM dual
UNION
SELECT 'CSW_USR_ROLE' FROM dual
UNION
SELECT 'CTXAPP' FROM dual
UNION
SELECT 'CWM_USER' FROM dual
UNION
SELECT 'DATAPUMP_EXP_FULL_DATABASE' FROM dual
UNION
SELECT 'DATAPUMP_IMP_FULL_DATABASE' FROM dual
UNION
SELECT 'DBA' FROM dual
UNION
SELECT 'DELETE_CATALOG_ROLE' FROM dual
UNION
SELECT 'EJBCLIENT' FROM dual
UNION
SELECT 'EXECUTE_CATALOG_ROLE' FROM dual
UNION
SELECT 'EXP_FULL_DATABASE' FROM dual
UNION
SELECT 'GATHER_SYSTEM_STATISTICS' FROM dual
UNION
SELECT 'GLOBAL_AQ_USER_ROLE' FROM dual
UNION
SELECT 'HS_ADMIN_EXECUTE_ROLE' FROM dual
UNION
SELECT 'HS_ADMIN_ROLE' FROM dual
UNION
SELECT 'HS_ADMIN_SELECT_ROLE' FROM dual
UNION
SELECT 'IMP_FULL_DATABASE' FROM dual
UNION
SELECT 'JAVADEBUGPRIV' FROM dual
UNION
SELECT 'JAVAIDPRIV' FROM dual
UNION
SELECT 'JAVASYSPRIV' FROM dual
UNION
SELECT 'JAVAUSERPRIV' FROM dual
UNION
SELECT 'JAVA_ADMIN' FROM dual
UNION
SELECT 'JAVA_DEPLOY' FROM dual
UNION
SELECT 'JMXSERVER' FROM dual
UNION
SELECT 'LBAC_DBA' FROM dual
UNION
SELECT 'LOGSTDBY_ADMINISTRATOR' FROM dual
UNION
SELECT 'MGMT_USER' FROM dual
UNION
SELECT 'OEM_MONITOR' FROM dual
UNION
SELECT 'OLAPI_TRACE_USER' FROM dual
UNION
SELECT 'OLAP_DBA' FROM dual
UNION
SELECT 'OLAP_USER' FROM dual
UNION
SELECT 'OLAP_XS_ADMIN' FROM dual
UNION
SELECT 'ORDADMIN' FROM dual
UNION
SELECT 'OWB$CLIENT' FROM dual
UNION
SELECT 'OWB_DESIGNCENTER_VIEW' FROM dual
UNION
SELECT 'OWB_USER' FROM dual
UNION
SELECT 'RECOVERY_CATALOG_OWNER' FROM dual
UNION
SELECT 'RESOURCE' FROM dual
UNION
SELECT 'SCHEDULER_ADMIN' FROM dual
UNION
SELECT 'SELECT_CATALOG_ROLE' FROM dual
UNION
SELECT 'SNMPAGENT' FROM dual
UNION
SELECT 'SPATIAL_CSW_ADMIN' FROM dual
UNION
SELECT 'SPATIAL_WFS_ADMIN' FROM dual
UNION
SELECT 'WFS_USR_ROLE' FROM dual
UNION
SELECT 'WM_ADMIN_ROLE' FROM dual
UNION
SELECT 'XDBADMIN' FROM dual
UNION
SELECT 'XDB_SET_INVOKER' FROM dual
UNION
SELECT 'XDB_WEBSERVICES' FROM dual
UNION
SELECT 'XDB_WEBSERVICES_OVER_HTTP' FROM dual
UNION
SELECT 'XDB_WEBSERVICES_WITH_PUBLIC' FROM dual
UNION 
SELECT 'APEX_ADMINISTRATOR_ROLE' FROM dual
UNION
SELECT 'DBFS_ROLE' FROM dual
UNION
SELECT 'OEM_ADVISOR' FROM dual
UNION
SELECT 'XFILES_ADMINISTRATOR' FROM dual
UNION
SELECT 'XFILES_USER' FROM dual
)
SELECT role
FROM   dba_roles
MINUS
SELECT *
FROM   def_roles;
